# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Comprehensive Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Comprehensive Assessment

pod 'Firebase/Auth'

pod 'Firebase/Firestore'

pod 'Firebase/Storage'

end


target 'Comprehensive AssessmentTests' do 
	inherit! :search_paths
	pod 'Firebase/Core'

end
